---
name: simple
"@id": "#simple"
description: "Schema for the SIMPLE Database"

######################################################
# CONVENTIONS
# - Source length is 50 characters
# - Reference is 30 characters. ivoa:ucd: meta.ref
# - Comments are 100 characters. ivoa:ucd: meta.note
# - Description is 100 characters. ivoa:ucd: meta.note
# - Values are datatype: double
# - Adopted: ivoa:ucd: meta.code
######################################################

tables:
#####################################################
# LOOKUP TABLES 
# These tables are expected and used by other tables
# ###################################################

  - name: Publications
    "@id": "#Publications"
    description: Reference information (DOI, bibcodes, etc)
    primaryKey: 
    - "#Publications.reference"

    columns:
    - name: reference
      "@id": "#Publications.reference"
      datatype: string
      length: 30
      description: Publication reference identifier
      ivoa:ucd: meta.ref;meta.main
      nullable: false
    - name: bibcode
      "@id": "#Publications.bibcode"
      datatype: string
      length: 100
      description: Publication bibcode
      ivoa:ucd: meta.bib.bibcode
    - name: doi
      "@id": "#Publications.doi"
      datatype: string
      length: 100
      description: Publication DOI
      ivoa:ucd: meta.ref.doi
    - name: description
      "@id": "#Publications.description"
      datatype: string
      length: 1000
      description: Publication description

  - name: Telescopes
    "@id": "#Telescopes"
    description: Telescope, mission, and survey information
    primaryKey: 
    - "#Telescopes.telescope"

    columns:
    - name: telescope
      "@id": "#Telescopes.telescope"
      datatype: string
      length: 30
      description: Telescope, mission, or survey name
      ivoa:ucd: meta.id;meta.main
      nullable: false
    - name: description
      "@id": "#Telescopes.description"
      datatype: string
      length: 1000
      description: Telescope description
      ivoa:ucd: meta.note
    - name: reference
      "@id": "#Telescopes.reference"
      datatype: string
      length: 30
      description: Publication reference; links to Publications table

    constraints:
      - name: Telescopes_reference_Publications_reference
        "@type": "ForeignKey"
        "@id": "#FK_Telescopes_reference_Publications_reference"
        description: Link Telescopes reference to Publications table
        columns:
        - "#Telescopes.reference"
        referencedColumns:
        - "#Publications.reference"

  - name: Instruments
    "@id": "#Instruments"
    description: Instrument information
    primaryKey: 
    - "#Instruments.instrument"
    - "#Instruments.mode"
    - "#Instruments.telescope"

    columns:
    - name: instrument
      "@id": "#Instruments.instrument"
      datatype: string
      length: 30
      description: Instrument name
      ivoa:ucd: instr;meta.main
      nullable: false
    - name: mode
      "@id": "#Instruments.mode"
      datatype: string
      length: 30
      description: Instrument mode
    - name: telescope
      "@id": "#Instruments.telescope"
      datatype: string
      length: 30
      description: Telescope, mission, or survey name; links to Telescopes table
    - name: description
      "@id": "#Instruments.description"
      datatype: string
      length: 1000
      description: Instrument description
      ivoa:ucd: meta.note
    - name: reference
      "@id": "#Instruments.reference"
      datatype: string
      length: 30
      description: Publication reference; links to Publications table
      ivoa:ucd: meta.ref

    constraints:
      - name: Instruments_reference_Publications_reference
        "@type": "ForeignKey"
        "@id": "#FK_Instruments_reference_Publications_reference"
        description: Link Instruments reference to Publications table
        columns:
        - "#Instruments.reference"
        referencedColumns:
        - "#Publications.reference"
      - name: Instruments_reference_Telescopes_telescope
        "@type": "ForeignKey"
        "@id": "#FK_Instruments_telescope_Telescopes_telescope"
        description: Link Instruments telescope to Telescopes table
        columns:
        - "#Instruments.telescope"
        referencedColumns:
        - "#Telescopes.telescope"

  - name: Parameters
    "@id": "#Parameters"
    description: Parameters lookup table
    primaryKey: 
    - "#Parameters.parameter"

    columns:
    - name: parameter
      "@id": "#Parameters.parameter"
      datatype: string
      length: 30
      description: Main identifier for a parameter
      ivoa:ucd: meta.id;meta.main
      nullable: false
    - name: description
      "@id": "#Parameters.description"
      datatype: string
      length: 1000
      description: Description of the parameter
      ivoa:ucd: meta.note

    indexes:
      - name: PK_Parameters
        "@id": "#PK_Parameters"
        description: Primary key for Parameters table
        columns: 
        - "#Parameters.parameter"

  - name: PhotometryFilters
    "@id": "#PhotometryFilters"
    description: Photometry filter information. This stores relationships between filters and instruments, telescopes, as well as wavelength and width
    primaryKey: 
    - "#PhotometryFilters.band"

    columns:
    - name: band
      "@id": "#PhotometryFilters.band"
      datatype: string
      length: 30
      description: Band name. Must be of the form instrument.filter
      ivoa:ucd: instr.bandpass;meta.main
      nullable: false
    - name: ucd
      "@id": "#PhotometryFilters.ucd"
      datatype: string
      length: 100
      description: Unified Content Descriptor of the photometry filter
    - name: effective_wavelength
      "@id": "#PhotometryFilters.effective_wavelength_angstroms"
      datatype: double
      description: Effective wavelength of the photometry filter in Angstroms
      fits:tunit: Angstrom
      nullable: false
    - name: width
      "@id": "#PhotometryFilters.width_angstroms"
      datatype: double
      fits:tunit: Angstrom
      description: Width of the ephotometry filter in Angstroms
      ivoa:ucd: instr.bandwidth

  # TODO: Consider constrait to avoid negative width

  - name: Versions
    "@id": "#Versions"
    description: Database version information
    primaryKey: 
    - "#Versions.version"

    columns:
    - name: version
      "@id": "#Versions.version"
      datatype: string
      length: 30
      description: Version identifier
      ivoa:ucd: meta.id;meta.main
      nullable: false
    - name: start_date
      "@id": "#Versions.start_date"
      datatype: string
      length: 30
      description: Date when this version started being used
    - name: end_date
      "@id": "#Versions.end_date"
      datatype: string
      length: 30
      description: Release date of this version
    - name: description
      "@id": "#Versions.description"
      datatype: string
      length: 1000
      description: Description of changes associated with this version

  - name: Regimes
    "@id": "#Regimes"
    description: Regime lookup table. Values used by Spectra and SpectralTypes tables
    primaryKey: 
    - "#Regimes.regime"

    columns:
    - name: regime
      "@id": "#Regimes.regime"
      datatype: string
      length: 30
      description: Regime identifier string
      ivoa:ucd: meta.id;meta.main
      nullable: false
    - name: description
      "@id": "#Regimes.description"
      datatype: string
      length: 1000
      description: Description of regime


  # Remove Gravity enum?

##########################################################
# MAIN TABLES
# Sources - primary table for the database 
# Names - used to store additional identifiers for sources
##########################################################

  - name: Sources
    "@id": "#Sources"
    description: "Main identifiers for objects along with coordinates."
    primaryKey:
    - "#Sources.source"

    columns:
    - name: source
      "@id": "#Sources.source"
      datatype: string
      length: 100
      description: Unique identifier for an object
      ivoa:ucd: meta.id;src;meta.main
      nullable: false
    - name: ra
      "@id": "#Sources.ra"
      datatype: double
      description: ICRS Right Ascension of object
      fits:tunit: deg
      ivoa:ucd: pos.eq.ra;meta.main
    - name: dec
      "@id": "#Sources.de"
      datatype: double
      description: ICRS Declination of object
      fits:tunit: deg
      ivoa:ucd: pos.eq.dec;meta.main
    - name: epoch
      "@id": "#Sources.epoch"
      datatype: double
      description: Decimal year for coordinates (eg, 2015.5)
      fits:tunit: yr
    - name: equinox
      "@id": "#Sources.equinox"
      datatype: string
      length: 10
      description: Equinox reference frame year (eg, J2000)
    - name: shortname
      "@id": "#Sources.shortname"
      datatype: string
      length: 30
      description: Short name for the source
      ivoa:ucd: meta.id;src
    - name: reference
      "@id": "#Sources.reference"
      datatype: string
      length: 30
      description: Publication reference; links to Publications table
      ivoa:ucd: meta.ref;meta.main
      nullable: false
    - name: other_references
      "@id": "#Sources.other_references"
      datatype: string
      length: 100
      description: Additional references
      ivoa:ucd: meta.ref
    - name: comments
      "@id": "#Sources.comments"
      datatype: string
      length: 1000
      description: Free-form comments on this Source
      ivoa:ucd: meta.note

    indexes:
      - name: PK_Sources_source
        "@id": "#PK_Sources_source"
        description: Primary key for Sources table
        columns: 
        - "#Sources.source"
    constraints:
      - name: check_ra
        "@type": Check
        "@id": "#Sources_check_ra_bounds"
        description: Validate RA range
        expression: ra_deg >= 0 AND ra_deg <= 360
      - name: check_dec
        "@type": Check
        "@id": "#Sources_check_dec_bounds"
        description: Validate Dec range
        expression: dec_deg >= -90 AND dec_deg <= 90
      - name: Source_reference_Publications_reference
        "@type": "ForeignKey"
        "@id": "#FK_Sources_reference_Publications_reference"
        description: Link Source reference to Publications table
        columns:
        - "#Sources.reference"
        referencedColumns:
        - "#Publications.reference"

  - name: Names
    "@id": "#Names"
    description: "Additional identifiers for objects in Sources table"
    primaryKey:
    - "#Names.source"
    - "#Names.other_name"

    columns:
    - name: source
      "@id": "#Names.source"
      datatype: string
      length: 100
      description: Main identifier for an object; links to Sources table
      ivoa:ucd: meta.id;meta.main
      nullable: false
    - name: other_name
      "@id": "#Names.other_name"
      datatype: string
      length: 100
      description: Alternate identifier for an object
      ivoa:ucd: meta.id
      nullable: false

    indexes:
      - name: PK_Names_source
        "@id": "#PK_Names_source"
        description: Primary key for Names table
        columns: 
        - "#Names.source"
        - "#Names.other_name"
    constraints:
      - name: Names_source_Source_source
        "@type": "ForeignKey"
        "@id": "#FK_Names_source_Source_source"
        description: Link Names primary identifer to Sources table
        columns:
        - "#Names.source"
        referencedColumns:
        - "#Sources.source"

##########################################################
# DATA TABLES
# These store data for the entries in the Sources table
##########################################################

  - name: Photometry
    "@id": "#Photometry"
    description: Photometry for Sources
    primaryKey: 
    - "#Photometry.source"
    - "#Photometry.band"
    - "#Photometry.reference"
  
    columns:
    - name: source
      "@id": "#Photometry.source"
      datatype: string
      length: 100
      description: Main identifier for an object; links to Sources table
      ivoa:ucd: meta.id;meta.main
      nullable: false
    - name: band
      "@id": "#Photometry.band"
      datatype: string
      length: 30
      description: Photometry band for this measurement; links to PhotometryFilters table
    - name: magnitude
      "@id": "#Photometry.magnitude"
      datatype: double
      description: Magnitude value for this entry
      fits:tunit: mag
      nullable: false
    - name: magnitude_error
      "@id": "#Photometry.magnitude_error"
      datatype: double
      description: Uncertainty of this magnitude value
      fits:tunit: mag
    - name: telescope
      "@id": "#Photometry.telescope"
      datatype: string
      length: 30
      description: Telescope, mission, or survey name; links to Telescopes table
    - name: epoch
      "@id": "#Photometry.epoch"
      datatype: double
      description: Decimal year
      fits:tunit: yr
    - name: comments
      "@id": "#Photometry.comments"
      datatype: string
      length: 1000
      description: Free-form comments for this entry
      ivoa:ucd: meta.note
    - name: reference
      "@id": "#Photometry.reference"
      datatype: string
      length: 30
      description: Publication reference; links to Publications table
      nullable: false

    indexes:
      - name: PK_Photometry
        "@id": "#PK_Photometry"
        description: Primary key for Photometry table
        columns: 
        - "#Photometry.source"
        - "#Photometry.band"
        - "#Photometry.reference"
    constraints:
      - name: Photometry_source_Sources_source
        "@type": "ForeignKey"
        "@id": "#FK_Photometry_source_Sources_source"
        description: Link Photometry source to Sources table
        columns:
        - "#Photometry.source"
        referencedColumns:
        - "#Sources.source"
      - name: Photometry_band_PhotometryFilters_band
        "@type": "ForeignKey"
        "@id": "#FK_Photometry_band_PhotometryFilters_band"
        description: Link Photometry band to PhotometryFilters table
        columns:
        - "#Photometry.band"
        referencedColumns:
        - "#PhotometryFilters.band"
      - name: Photometry_telescope_Telescopes_telescope
        "@type": "ForeignKey"
        "@id": "#FK_Photometry_telescope_Telescopes_telescope"
        description: Link Photometry telescope to Telescopes table
        columns:
        - "#Photometry.telescope"
        referencedColumns:
        - "#Telescopes.telescope"
      - name: Photometry_reference_Publications_reference
        "@type": "ForeignKey"
        "@id": "#FK_Photometry_reference_Publications_reference"
        description: Link Photometry reference to Publications table
        columns:
        - "#Photometry.reference"
        referencedColumns:
        - "#Publications.reference"

  - name: Parallaxes
  - name: ProperMotions
  - name: RadialVelocities
  - name: SpectralTypes
  - name: Gravities
  - name: Spectra
  - name: ModeledParameters
  - name: CompanionRelationships

  # Figure out how to handle views
