---
name: simple
"@id": "#simple"
description: "Schema for the SIMPLE Database"

######################################################
# CONVENTIONS
# - Source length is 50 characters
# - Reference is 30 characters. ivoa:ucd: meta.ref
# - Comments are 100 characters. ivoa:ucd: meta.note
# - Description is 100 characters. ivoa:ucd: meta.note
# - Values are datatype: double
# - Adopted: ivoa:ucd: meta.code
######################################################

tables:
#####################################################
# LOOKUP TABLES 
# These tables are expected and used by other tables
# ###################################################

  - name: Publications
    "@id": "#Publications"
    description: Reference information (DOI, bibcodes, etc)
    primaryKey: 
    - "#Publications.reference"

    columns:
    - name: reference
      "@id": "#Publications.reference"
      datatype: string
      length: 30
      description: Publication reference identifier
      ivoa:ucd: meta.ref;meta.main
      nullable: false
    - name: bibcode
      "@id": "#Publications.bibcode"
      datatype: string
      length: 100
      description: Publication bibcode
      ivoa:ucd: meta.bib.bibcode
    - name: doi
      "@id": "#Publications.doi"
      datatype: string
      length: 100
      description: Publication DOI
      ivoa:ucd: meta.ref.doi
    - name: description
      "@id": "#Publications.description"
      datatype: string
      length: 1000
      description: Publication description

  - name: Telescopes
    "@id": "#Telescopes"
    description: Telescope, mission, and survey information
    primaryKey: 
    - "#Telescopes.telescope"

    columns:
    - name: telescope
      "@id": "#Telescopes.telescope"
      datatype: string
      length: 30
      description: Telescope, mission, or survey name
      ivoa:ucd: meta.id;meta.main
      nullable: false
    - name: description
      "@id": "#Telescopes.description"
      datatype: string
      length: 1000
      description: Telescope description
      ivoa:ucd: meta.note
    - name: reference
      "@id": "#Telescopes.reference"
      datatype: string
      length: 30
      description: Publication reference; links to Publications table

    constraints:
      - name: Telescopes_reference_Publications_reference
        "@type": "ForeignKey"
        "@id": "#FK_Telescopes_reference_Publications_reference"
        description: Link Telescopes reference to Publications table
        columns:
        - "#Telescopes.reference"
        referencedColumns:
        - "#Publications.reference"

  - name: Instruments
    "@id": "#Instruments"
    description: Instrument information
    primaryKey: 
    - "#Instruments.instrument"
    - "#Instruments.mode"
    - "#Instruments.telescope"

    columns:
    - name: instrument
      "@id": "#Instruments.instrument"
      datatype: string
      length: 30
      description: Instrument name
      ivoa:ucd: instr;meta.main
      nullable: false
    - name: mode
      "@id": "#Instruments.mode"
      datatype: string
      length: 30
      description: Instrument mode
    - name: telescope
      "@id": "#Instruments.telescope"
      datatype: string
      length: 30
      description: Telescope, mission, or survey name; links to Telescopes table
    - name: description
      "@id": "#Instruments.description"
      datatype: string
      length: 1000
      description: Instrument description
      ivoa:ucd: meta.note
    - name: reference
      "@id": "#Instruments.reference"
      datatype: string
      length: 30
      description: Publication reference; links to Publications table
      ivoa:ucd: meta.ref

    constraints:
      - name: Instruments_reference_Publications_reference
        "@type": "ForeignKey"
        "@id": "#FK_Instruments_reference_Publications_reference"
        description: Link Instruments reference to Publications table
        columns:
        - "#Instruments.reference"
        referencedColumns:
        - "#Publications.reference"
      - name: Instruments_reference_Telescopes_telescope
        "@type": "ForeignKey"
        "@id": "#FK_Instruments_telescope_Telescopes_telescope"
        description: Link Instruments telescope to Telescopes table
        columns:
        - "#Instruments.telescope"
        referencedColumns:
        - "#Telescopes.telescope"

  - name: Parameters
    "@id": "#Parameters"
    description: Parameters lookup table
    primaryKey: 
    - "#Parameters.parameter"

    columns:
    - name: parameter
      "@id": "#Parameters.parameter"
      datatype: string
      length: 30
      description: Main identifier for a parameter
      ivoa:ucd: meta.id;meta.main
      nullable: false
    - name: description
      "@id": "#Parameters.description"
      datatype: string
      length: 1000
      description: Description of the parameter
      ivoa:ucd: meta.note

    indexes:
      - name: PK_Parameters
        "@id": "#PK_Parameters"
        description: Primary key for Parameters table
        columns: 
        - "#Parameters.parameter"

  - name: PhotometryFilters
    "@id": "#PhotometryFilters"
    description: Photometry filter information. This stores relationships between filters and instruments, telescopes, as well as wavelength and width
    primaryKey: 
    - "#PhotometryFilters.band"

    columns:
    - name: band
      "@id": "#PhotometryFilters.band"
      datatype: string
      length: 30
      description: Band name. Must be of the form instrument.filter
      ivoa:ucd: instr.bandpass;meta.main
      nullable: false
    - name: ucd
      "@id": "#PhotometryFilters.ucd"
      datatype: string
      length: 100
      description: Unified Content Descriptor of the photometry filter
    - name: effective_wavelength
      "@id": "#PhotometryFilters.effective_wavelength_angstroms"
      datatype: double
      description: Effective wavelength of the photometry filter in Angstroms
      fits:tunit: Angstrom
      nullable: false
    - name: width
      "@id": "#PhotometryFilters.width_angstroms"
      datatype: double
      fits:tunit: Angstrom
      description: Width of the ephotometry filter in Angstroms
      ivoa:ucd: instr.bandwidth

  # TODO: Consider constrait to avoid negative width

  - name: Versions
    "@id": "#Versions"
    description: Database version information
    primaryKey: 
    - "#Versions.version"

    columns:
    - name: version
      "@id": "#Versions.version"
      datatype: string
      length: 30
      description: Version identifier
      ivoa:ucd: meta.id;meta.main
      nullable: false
    - name: start_date
      "@id": "#Versions.start_date"
      datatype: string
      length: 30
      description: Date when this version started being used
    - name: end_date
      "@id": "#Versions.end_date"
      datatype: string
      length: 30
      description: Release date of this version
    - name: description
      "@id": "#Versions.description"
      datatype: string
      length: 1000
      description: Description of changes associated with this version

  - name: Regimes
    "@id": "#Regimes"
    description: Regime lookup table. Values used by Spectra and SpectralTypes tables
    primaryKey: 
    - "#Regimes.regime"

    columns:
    - name: regime
      "@id": "#Regimes.regime"
      datatype: string
      length: 30
      description: Regime identifier string
      ivoa:ucd: meta.id;meta.main
      nullable: false
    - name: description
      "@id": "#Regimes.description"
      datatype: string
      length: 1000
      description: Description of regime


  # Remove Gravity enum?

##########################################################
# MAIN TABLES
# Sources - primary table for the database 
# Names - used to store additional identifiers for sources
##########################################################

  - name: Sources
  - name: Names

##########################################################
# DATA TABLES
# These store data for the entries in the Sources table
##########################################################

  - name: Photometry
  - name: Parallaxes
  - name: ProperMotions
  - name: RadialVelocities
  - name: SpectralTypes
  - name: Gravities
  - name: Spectra
  - name: ModeledParameters
  - name: CompanionRelationships

  # Figure out how to handle views
