db_name = "simple_tests"
data_path = "data/"
felis_path = "schema.yaml"

lookup_tables = [
    "Publications",
    "Telescopes",
    "Instruments",
    "Parameters",
    "PhotometryFilters",
    "Versions",
    "RegimeList",
    "CompanionList",
]