from convert_spectra_to_spec1dfits import *
from astropy.table import Table
import astropy.units as u


# Function for reading in the Suarez .dat files
def spectrum_loader(spectrum_path):
    print(spectrum_path)
    spectrum_table = Table.read(spectrum_path, format='ascii', names=['wavelength', 'flux', 'flux_uncertainty'])
    return spectrum_table


table_file = 'Suarez22.csv'

spectra_data_info = {
    'data': Table.read(table_file),  # TODO: take out of dictionary
    'original_data_dir': None,
    'fits_data_dir': 'Suarez2022_kc/',

    # Information about the spectra
    'wavelength_unit': u.micron,
    'flux_unit': u.Jy,
    'bandpass': None,
    'aperture': None,
    "obs_location": None,
    'voclass': None,  # corresponds to IVOA data model

    # Information about the publications the data come from
    'title': 'IRS Spectra of Brown Dwarfs from Suarez & Metchev 2022',
    'bibcode': '2022MNRAS.513.5701S',
    'author': 'Suarez, Genaro; Metchev, Stanimir',
    'doi': ' 10.1093/mnras/stac1205',
    'spectra_comments': None,  # Any comments about the data provenance

    # Column Names
    "startline" : None,
    "object_name_column": 'Source',
    "spectrum_path_column": 'Spectrum',
    "RA_column_name": 'RA',
    "dec_column_name": 'dec',
    "start_time_column_name ": 'start time',
    "stop_time_column_name ": 'stop time',
    "exposure_time_column_name": 'exposure time',
    "instrument_column_name": 'instrument',
    "observation_date_column_name": 'observation_date',
    "telescope_column_name": 'telescope',

    'vopub': 'SIMPLE Archive', # If going to be served via SIMPLE
    'generated_history': 'This file generated by convert_spectra_to_spec1dfits.py',

    'loader_function': spectrum_loader,

}

convert_to_fits(spectra_data_info)

# TODO: script should loop over file and function called once per file
#  for i, file in enumerate(files):
#        convert_to_fits(file, spectral_data_info)
