
#get rid of extra " " in object names
#think about improving file name - instument? telescope?
# get rid of %2B in file name (object name rather than file name?)

#final pull request will include this script
#spectra uplaoded by kelle to aws
#rename  convert_ipac_txt.py
#pull request w id unreable spectra

#make annual report -> on the blog
# reu program, talk , grant

from convert_spectra_to_spec1dfits import *
from astropy.io import ascii
import astropy.units as u
import requests

table='/Users/jolie/gitlocation/SIMPLE-db/scripts/spectra_convert/not_working_txt_table.dat'
data = ascii.read(table)


def text_spectrum_loader(spectrum_path):
        spectrum_table = ascii.read(spectrum_path)
        spectrum_table['flux_density'].name = 'flux'
        spectrum_table['error'].name = 'flux_uncertainty'
        spectrum_table['wavelength'].unit = u.um
        return spectrum_table

for row in data:
    spectrum_path = (row[0])
    try:
        requests.get(spectrum_path)
        dat = ascii.read(spectrum_path)
        original_header_dict = dat.meta['keywords']
        if original_header_dict['AOT_TYPE']['value'] == 'IrsStare' :
            insturment = "IRS"
        else:
            insturment = None
        dataset_dict = {
            'loader_function': text_spectrum_loader,
            'file_path': spectrum_path,
            'fits_data_dir': '/Users/jolie/gitlocation/SIMPLE-db/scripts/spectra_convert/data/',  # Path of FITS output
            # Information about new spectra
            'vopub': 'SIMPLE Archive',  # SIMPLE Archive, if going to be served via SIMPLE
            'generated_history': 'This file generated by convert_ipac_txt.py',
            'object_name' : original_header_dict['OBJECT']['value'].translate({ord("'"): None}).split('/')[0],
            'telescope': original_header_dict['TELESCOP']['value'],
            'instrument': insturment

        }

        #object_name = dataset_dict['object_name']
        print(dataset_dict['object_name'])

        text_spectrum_loader(spectrum_path)
        new_dict = {**original_header_dict, **dataset_dict} #header dictionary shoudl go first bc new info goes at bottom

        convert_to_fits(new_dict)
    except :
        pass
