from convert_spectra_to_spec1dfits import *
from astropy.io import ascii
import astropy.units as u
import requests

table='/Users/jolie/gitlocation/SIMPLE-db/scripts/spectra_convert/not_working_txt_table.dat'
data = ascii.read(table)

for row in data:
    spectrum_path = (row[0])
    try:
        def text_spectrum_loader(spectrum_path):
            spectrum_table = ascii.read(spectrum_path)
            spectrum_table['flux_density'].name = 'flux'
            spectrum_table['error'].name = 'flux_uncertainty'
            spectrum_table['wavelength'].unit = u.um
            return spectrum_table
        requests.get(spectrum_path)
        dat = ascii.read(spectrum_path)
        original_header_dict = dat.meta['keywords']

        dataset_dict = {
            'loader_function': text_spectrum_loader,
            'file_path': spectrum_path,
            'fits_data_dir': '/Users/jolie/gitlocation/SIMPLE-db/scripts/spectra_convert/data/',  # Path of FITS output
            # Information about new spectra
            'vopub': 'SIMPLE Archive',  # SIMPLE Archive, if going to be served via SIMPLE
            'generated_history': 'This file generated by convert_ipac_txt.py',
            'object_name' : original_header_dict['OBJECT']['value'],
            'telescope': original_header_dict['TELESCOP']['value'],
            'instrument': None

        }


        text_spectrum_loader(spectrum_path)

        new_dict = {**original_header_dict, **dataset_dict} #header dictionary shoudl go first bc new info goes at bottom

        convert_to_fits(new_dict)
    except :
        pass
