name: Missing Data
description: Report missing data from the database
title: 'Data ingest request from: <publication>'
labels: ["data ingestion"]
assignees: ''

---
body:
  - type: textarea
    attributes:
      label: source name
      description: Source/survey/catalogue name(s)
    validations:
      required: true
  - type: textarea
    attributes:
      label: link
      description: SIMBAD/CDS/Vizier link to data source(s), if available
    validations:
      required: false
  - type: textarea
    attributes:
      label: data
      description: Describe the data that needs to be added
    validations:
      required: false
  - type: textarea
    attributes:
      label: ref
      description: Reference(s) paper for the data
    validations:
      required: false
  - type: textarea
    attributes:
    label: Anything else?
    description: |
      Anything that will give us more context about the data you think needs to be added.
    validations:
      required: false
