# This workflow will install Python dependencies,
# run the python script to generate the database,
# and upload the regenerated database to the binary repo

name: Generate Database

on:
  # More details on trigger events: 
  #  https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:  # manual execution
  release:
    types: [published]

jobs:
  build:
    # Only run for the SIMPLE-AstroDB/SIMPLE-db repo, not on any forks
    if: github.repository == 'SIMPLE-AstroDB/SIMPLE-db'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: uv sync

    - name: Generate sqlite (file) database
      run: uv run python simple/utils/generate_database.py

    - name: Checkout destination repo
      uses: actions/checkout@v4
      with:
        repository: SIMPLE-AstroDB/SIMPLE-binary
        path: SIMPLE-binary
        token: ${{ secrets.SIMPLE_TOKEN }}

    - name: Push database file
      run: |
        cp SIMPLE.sqlite SIMPLE-binary/SIMPLE.sqlite
        cp database.toml SIMPLE-binary/database.toml
        cd SIMPLE-binary
        git config user.email "github-actions@github.com"
        git config user.name "github-actions"
        git add SIMPLE.sqlite
        git add database.toml
        git commit -m "Update SIMPLE.sqlite and database.toml from SIMPLE-db release ${{ github.ref_name }}" || echo "No changes to commit"
        git push
